apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-web.fullname" . }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "simple-web.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deploymentMaxSurge}}
      maxUnavailable: {{ .Values.deploymentMaxUnavailable}}
  template:
    metadata:
      labels:
        {{- include "simple-web.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
          command: {{ .Values.appCommand | toYaml | nindent 12 }}
          args: {{ .Values.appArgs | toYaml | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.appReadOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.appAllowPrivilegeEscalation }}
            runAsNonRoot: {{ .Values.appRunAsNonRoot }}
            runAsUser: {{ .Values.appRunAsUser }}
          ports:
            - containerPort: {{ .Values.appContainerPort }}
          resources:
            requests:
              cpu: {{ .Values.appCpuRequests }}
              memory: {{ .Values.appMemoryRequests }}
            limits:
              cpu: {{ .Values.appCpuLimits }}
              memory: {{ .Values.appMemoryLimits }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbePath }}
              port: {{ .Values.livenessProbePort }}
            initialDelaySeconds: {{ .Values.livenessProbeInitialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbePeriodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbePath }}
              port: {{ .Values.readinessProbePort }}
            initialDelaySeconds: {{ .Values.readinessProbeInitialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbePeriodSeconds }}
          volumeMounts:
            - name: code
              mountPath: /code
          
      initContainers:
        - name: init-{{ .Release.Name }}
          image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
          command:
            - sh
            - -c
            - |
              cp -a /code/. /shared-code && \
              chmod -R 755 /shared-code && \
              chown -R 1000:1000 /shared-code
          resources:
            requests:
              cpu: {{ .Values.initCpuRequests }}
              memory: {{ .Values.initMemoryRequests }}
            limits:
              cpu: {{ .Values.initCpuLimits }}
              memory: {{ .Values.initMemoryLimits }}
          volumeMounts:
            - name: code
              mountPath: /shared-code
      imagePullSecrets:
        - name: {{ include "simple-web.imagePullSecretName" . }}
      volumes:
        - name: code
          emptyDir: {}