apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-web.fullname" . }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "simple-web.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deploymentMaxSurge}}
      maxUnavailable: {{ .Values.deploymentMaxUnavailable}}
  template:
    metadata:
      labels:
        {{- include "simple-web.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
          securityContext:
            readOnlyRootFilesystem: false # the app requires writing data to implement its counter functionality.
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["NET_BIND_SERVICE"] # Allows binding to port 80 without allowing the other unnecessary capabilities
          ports:
            - containerPort: {{ .Values.appContainerPort }}
          # tighten later by using a busybox deployment to check actual resource usage
          resources:
            requests:
              cpu: {{ .Values.deploymentCpuRequests }}
              memory: {{ .Values.deploymentMemoryRequests }}
            limits:
              cpu: {{ .Values.deploymentCpuLimits }}
              memory: {{ .Values.deploymentMemoryLimits }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbePath }}
              port: {{ .Values.livenessProbePort }}
            initialDelaySeconds: {{ .Values.livenessProbeInitialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbePeriodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbePath }}
              port: {{ .Values.readinessProbePort }}
            initialDelaySeconds: {{ .Values.readinessProbeInitialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbePeriodSeconds }}

      
      imagePullSecrets:
      - name: {{ include "simple-web.imagePullSecretName" . }}
