apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-web.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "simple-web.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deploymentMaxSurge}}
      maxUnavailable: {{ .Values.deploymentMaxUnavailable}}
  template:
    metadata:
      labels:
        {{- include "simple-web.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
          ports:
            - containerPort: {{ .Values.appContainerPort }}
          # tighten later by using a busybox deployment to check actual resource usage
          resources:
            requests:
              cpu: {{ .Values.deploymentCpuRequests }}
              memory: {{ .Values.deploymentMemoryRequests }}
            limits:
              cpu: {{ .Values.deploymentCpuLimits }}
              memory: {{ .Values.deploymentMemoryLimits }}
            livenessProbe:
              httpGet:
                path: {{ .Values.livenessProbePath }}
                port: {{ .Values.livenessProbePort }}
              initialDelaySeconds: {{ .Values.livenessProbeInitialDelaySeconds }}
              periodSeconds: {{ .Values.livenessProbePeriodSeconds }}
            readinessProbe:
              httpGet:
                path: {{ .Values.readinessProbePath }}
                port: {{ .Values.readinessProbePort }}
              initialDelaySeconds: {{ .Values.readinessProbeInitialDelaySeconds }}
              periodSeconds: {{ .Values.readinessProbePeriodSeconds }}

      
      imagePullSecrets:
      - name: {{ include "simple-web.imagePullSecretName" . }}
