apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-web.fullname" . }}
  annotations:
    # app needs route "/" ingress needs "/benl"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingressTargetPath }}
spec: 
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingressRulePath }}
            pathType: {{ .Values.ingressRulePathType }}
            backend:  
              service:
                name: {{ include "simple-web.fullname" . }}
                port:
                  number: {{ .Values.serviceClusterPort }}