apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "simple-web.scaledObjectName" . }}
spec:
  scaleTargetRef:
    name: {{ include "simple-web.fullname" . }}
  minReplicaCount: {{ .Values.kedaMinReplicaCount | default 2 }}
  maxReplicaCount: {{ .Values.kedaMaxReplicaCount }}
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: {{ .Values.kedaCpuTriggerValue | quote }}
    - type: memory
      metadata:
        type: Utilization
        value: {{ .Values.kedaMemoryTriggerValue | quote }}
    - type: cron
      metadata:
        timezone: {{ .Values.kedaCronTriggerTimezone | quote }}
        start: {{ .Values.kedaCronTriggerStart | quote }}
        end: {{ .Values.kedaCronTriggerEnd | quote }}
        desiredReplicas: {{ .Values.kedaCronTriggerDesiredReplicas | quote }}
