apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    {{- include "simple-web.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.serviceClusterPort }}
      targetPort: {{ .Values.serviceTargetPort }}
