#############
# Deployment
#############

replicaCount: 2
image: 
  repository: acrinterview.azurecr.io/simple-web
  tag: latest
labels:
  app: simple-web

appContainerPort: 80
# Resources
deploymentCpuRequests: "200m"
deploymentMemoryRequests: "128Mi"
deploymentCpuLimits: "500m"
deploymentMemoryLimits: "512Mi"
# Rolling update
deploymentMaxSurge: "25%"
deploymentMaxUnavailable: 0

#############
# Pull Secret
#############
secretName: acr-pull-secret
secretType: kubernetes.io/dockerconfigjson

#############
# Service
#############
serviceName: simple-web
serviceType: NodePort
servicePort:
  cluster: 80
  target: 80
  nodePort: 30004

#############
# Ingress
#############
ingressClassName: nginx

#################
# KEDA Autoscaler
#################
kedaMinReplicaCount: 2
kedaMaxReplicaCount: 10
kedaCpuTriggerValue: "70"
kedaMemoryTriggerValue: "80"

