#############
# Deployment
#############

replicaCount: 2 
imageRepository: acrinterview.azurecr.io/simple-web
imageTag: latest
labels:
  app: simple-web

appContainerPort: 80

# Resources
deploymentCpuRequests: "50m"
deploymentMemoryRequests: "64Mi"
deploymentCpuLimits: "200m"
deploymentMemoryLimits: "128Mi"

# Rolling update
deploymentMaxSurge: "25%"
deploymentMaxUnavailable: 0

#############
# Pull Secret
#############
secretSuffix: image-pull-secret
secretType: kubernetes.io/dockerconfigjson

#############
# Service
#############
serviceName: simple-web
serviceType: ClusterIP
serviceClusterPort: 80
serviceTargetPort: 80

#############
# Ingress
#############
ingressClassName: nginx
ingressRulePath: /benl
ingressRulePathType: Prefix
ingressTargetPath: /

#################
# KEDA Autoscaler
#################
kedaMinReplicaCount: 2
kedaMaxReplicaCount: 10
kedaCpuTriggerValue: "70"
kedaMemoryTriggerValue: "80"
kedaCronTriggerTimezone: "Asia/Jerusalem"
kedaCronTriggerStart: "0 8 * * *"
kedaCronTriggerEnd: "0 00 * * *"
kedaCronTriggerDesiredReplicas: "5"

