apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-web.imagePullSecretName" . }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
data:
  # Value must be base64 encoded and injected at deployment time using --set.
  .dockerconfigjson: {{ .Values.secretValue }}
type: {{ .Values.secretType }}
