apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "simple-web.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: {{ .Values.pvcStorageClass}}
  resources:
    requests:
      storage: {{ .Values.pvcStorageAmount }}