apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-web.fullname" . }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    {{- include "simple-web.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.serviceClusterPort }}
      targetPort: {{ .Values.serviceTargetPort }}
