apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-web.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-web.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.appContainerPort }}
      imagePullSecret:
      - name: {{ .Values.secretName }}
